name: Scan

on:
  workflow_run:
    workflows: ["CICD"]
    types:
      - completed
  schedule:
    - cron: "25 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set docker image names.
      - name: Setup env variables
        run: |
          echo "DOCKER_SERVICE=kvalitetsit/kithugs-trivy" >> $GITHUB_ENV

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Ppull
        run: docker pull ${{ env.DOCKER_SERVICE }}:dev

      - name: Run Trivy vulnerability scanner json
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.DOCKER_SERVICE }}:dev'
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'

      - name: Show Trivy
        run: cat trivy-results.json

      - name: Trivy upload
        run: |
          curl -v -X POST -H 'X-KEY: ${{ secrets.TRIVY_KEY }}' -H 'Content-Type: application/json' -d @trivy-results.json ${{ secrets.TRIVY_ENDPOINT }}

      - uses: knqyf263/trivy-issue-action@v0.0.3
        with:
          # Label name
          # Default: vulnerability (this label must be created in advance)
          label: 'dependencies'

          # Severities of vulnerabilities to be registered to GitHub Issues
          # Default: 'CRITICAL'
          severity: 'CRITICAL,HIGH'

